const bankAccount = {
    "bankAccountId": "E212-B-LIMA5",//which is autogenerated
    "accountNumber": 1010203040 ,
    "credentials" : [{'username' : "harana",
                     'password' : "parokya", 
                     'pin' : 1234,}],//which is an array with username, password and pin
    "balance" : 10000,//which is an amount of money
    "createdAt" : "November 16, 2022",//which is a date
    "account" : function(){
            console.log(this.bankAccountId)
            console.log(this.accountNumber)
            for (details of this.credentials){
                console.log(details.username)
                console.log(details.password)
                console.log(details.pin)}
            console.log(this.balance)
            console.log(this.createdAt)
            }
};
bankAccount.account();