const userAccount = {
    "bankAccount":[{
        "bankAccountId": "E212-B-LIMA5",//which is autogenerated
        "accountNumber": 1010203040 ,
        'username' : "harana",
        'password' : "parokya", 
        'pin' : 1234,//which is an array with username, password and pin
        "balance" : 10000,//which is an amount of money
        "createdAt" : "November 16, 2022"}],//which is a date
    "debitCArd" : 101020304050, //Which is a card number.
    "firstName" : "Louver Rai",
    "lastName" : "Corpus" ,
    "birthDate" : "November 1, 2000",
    "validID" : [{  "ID1" : "passport",
                        "IDno1" : 12345678900,
                        "ID2" : "driver's license",
                        "IDno2" : 12345678901}],
        "address" : "Poblacion, Tagaytay City, Cavite",
    "displayUserAccount" : function(){
            for (details of this.bankAccount)
            console.log(details.bankAccountId)
            console.log(details.accountNumber)
            console.log(details.username)
            console.log(details.password)
            console.log(details.pin)
            console.log(details.balance)
            console.log(details.createdAt)
            console.log(this.debitCArd)
            console.log(this.firstName , this.lastName)
            console.log(this.birthDate)
            for (details of this.validID){
                console.log(details.ID1) 
                console.log(details.IDno1)
                console.log(details.ID2)
                console.log(details.IDno2)
            }
            console.log(this.address)
        }   };
    userAccount.displayUserAccount();